// DigComp 3.0 — Reference data + question bank
// Source: Cosgrove & Cachia, JRC144121, EUR 40491, doi:10.2760/0001149 (27 Nov 2025)

window.DIGCOMP3_META = {
  title: "DigComp 3.0",
  subtitle: "European Digital Competence Framework — 5th edition",
  authors: "Cosgrove & Cachia",
  jrc: "JRC144121",
  doi: "10.2760/0001149",
  published: "27 November 2025",
  publisher: "Joint Research Centre, European Commission",
  licence: "CC BY 4.0",
  url: "https://publications.jrc.ec.europa.eu/repository/handle/JRC144121"
};

window.DIGCOMP3_AREAS = [
  { n: 1, was: "Information and data literacy", now: "Information search, evaluation and management" },
  { n: 2, was: "Communication and collaboration", now: "Communication and collaboration" },
  { n: 3, was: "Digital content creation", now: "Content creation" },
  { n: 4, was: "Safety", now: "Safety, wellbeing and responsible use" },
  { n: 5, was: "Problem solving", now: "Problem identification and solving" }
];

window.DIGCOMP3_RENAMES = [
  { c: "1.1", was: "Browsing, searching and filtering data, information and digital content", now: "Browsing, searching and filtering information" },
  { c: "1.2", was: "Evaluating data, information and digital content", now: "Evaluating information" },
  { c: "1.3", was: "Managing data, information and digital content", now: "Managing information" },
  { c: "2.1", was: "Interacting through digital technologies", now: "Interacting through and with digital technologies" },
  { c: "2.5", was: "Netiquette", now: "Digital behaviour", important: true },
  { c: "3.4", was: "Programming", now: "Computational thinking and programming", important: true },
  { c: "4.3", was: "Protecting health and well-being", now: "Supporting wellbeing", important: true },
  { c: "4.4", was: "Protecting the environment", now: "Environmental impacts of digital technologies", important: true },
  { c: "5.1", was: "Solving technical problems", now: "Identifying and solving technical problems" },
  { c: "5.2", was: "Identifying needs and technological responses", now: "Identifying needs and digital technological responses" },
  { c: "5.3", was: "Creatively using digital technologies", now: "Identifying creative solutions using digital technologies" },
  { c: "5.4", was: "Identifying digital competence gaps", now: "Identifying and addressing digital competence needs" }
];

window.DIGCOMP3_HIGHLIGHTS = [
  { h: "Same skeleton, new flesh", t: "Still 5 areas and 21 competences. The structure is unchanged; the content underneath is rebuilt." },
  { h: "Proficiency: 8 → 4", t: "Eight levels collapse into four: Basic, Intermediate, Advanced, Highly advanced. The old top label \"Highly specialised\" is gone." },
  { h: "523 learning outcomes", t: "Brand-new layer split into 217 knowledge / 199 skills / 107 attitudes. The 2.2 \"Dimension 4 examples\" are replaced by 362 competence statements + these 523 outcomes." },
  { h: "AI is everywhere", t: "AI competence is woven across all 21 competences with [AI-E] / [AI-I] labels. About 14% of competence statements are AI-explicit, 68% AI-implicit." },
  { h: "AI defined by the AI Act", t: "DigComp 3.0 adopts the verbatim Article 3(1) AI Act definition. Generative AI gets a separate definition (subset of AI; ML models producing text/image/audio)." },
  { h: "Netiquette is dead", t: "Competence 2.5 is renamed Digital behaviour — broader scope, less courtesy-manual feel." },
  { h: "Programming grew up", t: "3.4 is now Computational thinking and programming, with computational thinking declared a transversal competence." },
  { h: "Wellbeing, not protection", t: "4.3 shifts from defensive (\"Protecting health and well-being\") to proactive (\"Supporting wellbeing\") — covers cyberbullying, deceptive patterns, balance." },
  { h: "Environmental impact, not protection", t: "4.4 expands beyond \"Protecting the environment\" to the full ICT lifecycle: production, operation, repair, recycling, disposal, data centres." },
  { h: "~120-term Glossary", t: "First DigComp version with a consolidated glossary, including AI system, generative AI, deceptive patterns (formerly dark patterns), filter bubble, deep-fake, gamification." }
];

window.DIGCOMP3_EPSO_NOTE = "EPSO's AD5/2026 Notice of Competition (EPSO/AD/427/26) explicitly references DigComp 2.2, not 3.0. DigComp 3.0 was published only weeks before the AD5/2026 application window opened. For the 2026 test, master 2.2 first; treat 3.0 as supplementary background. The renames above are the highest-yield items if EPSO updates the framework reference for a future cycle.";

window.DIGCOMP3_QUESTIONS = [
  { i: "d3.01", c: "d3", t: "Publication year", d: 1, q: "DigComp 3.0 was officially published by the European Commission's Joint Research Centre in:", o: ["2022", "2024", "2025", "2027"], a: 2, e: "DigComp 3.0 (JRC144121) was published on 27 November 2025, three years after DigComp 2.2 (JRC128415, March 2022)." },
  { i: "d3.02", c: "d3", t: "Areas count", d: 1, q: "How many competence areas does DigComp 3.0 have?", o: ["3", "5", "7", "21"], a: 1, e: "DigComp 3.0 retains the five competence areas of earlier versions. The total of 21 competences is also unchanged." },
  { i: "d3.03", c: "d3", t: "Competences count", d: 1, q: "How many competences does DigComp 3.0 contain?", o: ["18", "20", "21", "23"], a: 2, e: "21 competences across 5 areas — unchanged from DigComp 2.1 and 2.2. The structure is preserved; the content underneath is rebuilt." },
  { i: "d3.04", c: "d3", t: "Proficiency levels", d: 2, q: "DigComp 3.0 reduces the number of proficiency levels from 8 in DigComp 2.2 to:", o: ["3", "4", "5", "6"], a: 1, e: "DigComp 3.0 has four proficiency levels: Basic, Intermediate, Advanced, and Highly advanced. The eight-level scheme of 2.1 / 2.2 is collapsed; the old top label 'Highly specialised' is replaced by 'Highly advanced'." },
  { i: "d3.05", c: "d3", t: "Top proficiency label", d: 2, q: "What is the highest proficiency level in DigComp 3.0?", o: ["Highly specialised", "Expert", "Highly advanced", "Master"], a: 2, e: "The four levels are Basic, Intermediate, Advanced, Highly advanced. 'Highly specialised' was the top label in 2.1 / 2.2 — and is explicitly replaced. Highly advanced is not the same as ICT-specialist skills." },
  { i: "d3.06", c: "d3", t: "Area 1 rename", d: 2, q: "In DigComp 3.0, Area 1 — formerly 'Information and data literacy' — is renamed:", o: ["Data and AI literacy", "Information search, evaluation and management", "Digital information", "Searching and filtering"], a: 1, e: "Area 1 is now 'Information search, evaluation and management', emphasising the active processes citizens carry out rather than the abstract 'literacy' framing." },
  { i: "d3.07", c: "d3", t: "Area 4 rename", d: 2, q: "In DigComp 3.0, Area 4 — formerly 'Safety' — is renamed:", o: ["Cybersecurity and trust", "Safety, wellbeing and responsible use", "Protection and privacy", "Digital safety"], a: 1, e: "Area 4 broadens from 'Safety' to 'Safety, wellbeing and responsible use', reflecting the proactive shift in 4.3 (Supporting wellbeing) and the lifecycle scope of 4.4 (Environmental impacts)." },
  { i: "d3.08", c: "d3", t: "Area 5 rename", d: 2, q: "In DigComp 3.0, Area 5 — formerly 'Problem solving' — is renamed:", o: ["Problem identification and solving", "Digital problem solving", "Solutions and innovation", "Critical problem solving"], a: 0, e: "Area 5 becomes 'Problem identification and solving' to highlight that recognising the problem is itself a competence — not just executing a fix." },
  { i: "d3.09", c: "d3", t: "Netiquette renamed", d: 2, q: "In DigComp 3.0, the competence formerly called 'Netiquette' (2.5) is now called:", o: ["Online manners", "Digital behaviour", "Communication etiquette", "Digital citizenship"], a: 1, e: "Competence 2.5 is renamed 'Digital behaviour' — broader and more neutral than 'Netiquette', covering professional conduct, inclusive communication, and respect across digital environments." },
  { i: "d3.10", c: "d3", t: "Programming renamed", d: 2, q: "Competence 3.4 in DigComp 2.2 was 'Programming'. In DigComp 3.0 it is renamed:", o: ["Coding and software", "Computational thinking and programming", "Algorithms and code", "Programming and AI"], a: 1, e: "3.4 is now 'Computational thinking and programming'. Computational thinking is declared a transversal competence (per the ICILS definition), kept under Area 3 only for structural consistency with the previous version." },
  { i: "d3.11", c: "d3", t: "4.3 renamed", d: 2, q: "Competence 4.3, previously 'Protecting health and well-being', is renamed in DigComp 3.0 to:", o: ["Digital wellness", "Health and balance online", "Supporting wellbeing", "Wellbeing and disconnect"], a: 2, e: "4.3 shifts from a defensive framing ('Protecting…') to a proactive one ('Supporting wellbeing'), expanding to physical, mental and social dimensions." },
  { i: "d3.12", c: "d3", t: "4.4 renamed", d: 2, q: "Competence 4.4 in DigComp 3.0 — formerly 'Protecting the environment' — is renamed:", o: ["Green digital skills", "Environmental impacts of digital technologies", "Sustainable computing", "Digital sustainability"], a: 1, e: "4.4 expands from narrow 'protection' to 'Environmental impacts of digital technologies' — covering device production, operation, repair, recycling, disposal, data centres, and energy consumption across the ICT lifecycle." },
  { i: "d3.13", c: "d3", t: "AI definition source", d: 3, q: "DigComp 3.0 defines an 'AI system' using the verbatim definition from:", o: ["Article 3(1) of the EU AI Act", "The OECD AI Principles", "Article 22 of GDPR", "The UNESCO AI Ethics Recommendation"], a: 0, e: "DigComp 3.0 adopts the AI system definition from Article 3(1) of Regulation (EU) 2024/1689 (the AI Act) — a machine-based system operating with varying autonomy that infers from input how to generate outputs influencing physical or virtual environments." },
  { i: "d3.14", c: "d3", t: "AI integration", d: 2, q: "How is AI competence integrated in DigComp 3.0?", o: ["As a new sixth competence area", "As a new 22nd competence", "Transversally across all 21 competences with [AI-E] / [AI-I] labels", "Only in Area 3 (Content creation)"], a: 2, e: "AI competence is woven through all 21 competences. Items are labelled [AI-E] for AI-explicit and [AI-I] for AI-implicit. Roughly 14% of competence statements are AI-explicit, 68% AI-implicit, 18% neither." },
  { i: "d3.15", c: "d3", t: "New competences added", d: 2, q: "How many new competences are added in DigComp 3.0 versus DigComp 2.2?", o: ["None — the total stays at 21", "One — for AI literacy", "Two — for AI and sustainability", "Five — one per area"], a: 0, e: "Zero new competences. The structure stays at 5 areas and 21 competences. New emphasis is delivered through renaming, revised competence statements, and 523 new learning outcomes — not through adding boxes." },
  { i: "d3.16", c: "d3", t: "Learning outcomes", d: 3, q: "DigComp 3.0 introduces a new layer of 'learning outcomes' totalling approximately:", o: ["120", "240", "360", "520"], a: 3, e: "DigComp 3.0 contains 523 learning outcomes, split into 217 knowledge, 199 skills, and 107 attitudes. They replace (with competence statements) the 2.2 'Dimension 4 examples'." },
  { i: "d3.17", c: "d3", t: "Generative AI", d: 2, q: "DigComp 3.0 explicitly defines 'generative AI' as:", o: ["The same as artificial intelligence", "A subset of AI using specialised ML models capable of producing text, images, audio and similar outputs", "A search engine technology", "A type of cybersecurity tool"], a: 1, e: "Generative AI is defined as a subset of AI using specialised machine-learning models designed to produce a variety of outputs (text, image, audio). The definition was added because ChatGPT (Nov 2022) post-dated DigComp 2.2's March 2022 cut-off." },
  { i: "d3.18", c: "d3", t: "Reality-virtuality", d: 3, q: "Which concept is newly introduced in DigComp 3.0 to describe immersive interaction?", o: ["The metaverse", "The reality-virtuality continuum", "The digital twin", "Web 3.0"], a: 1, e: "DigComp 3.0 introduces the 'reality-virtuality continuum' (CS2.1.07), distinguishing physical and virtual realities and covering AR, VR, MR and XR. 'Metaverse' is not used as a headline framework term." },
  { i: "d3.19", c: "d3", t: "Pre-bunking", d: 3, q: "Which technique against disinformation is newly addressed in DigComp 3.0 explicitly?", o: ["Encryption", "Pre-bunking and de-bunking", "Two-factor authentication", "Open data licensing"], a: 1, e: "Competence 1.2 includes explicit competence statements on pre-bunking (inoculating audiences before exposure) and de-bunking (correcting after the fact), alongside filter bubbles, clickbait, nudging and gamification." },
  { i: "d3.20", c: "d3", t: "Deceptive patterns", d: 2, q: "In the DigComp 3.0 Glossary, the term 'deceptive patterns' is noted as:", o: ["A new concept invented in 2025", "Formerly referred to as 'dark patterns'", "A type of cyberattack", "Synonymous with phishing"], a: 1, e: "The Glossary entry for 'deceptive patterns' explicitly notes they were formerly referred to as dark patterns. The terminology shift reflects current EU policy language under the Digital Services Act." },
  { i: "d3.21", c: "d3", t: "Glossary", d: 1, q: "DigComp 3.0 introduces — for the first time in the DigComp series — a:", o: ["Set of test questions", "Consolidated Glossary of around 120 terms", "Mandatory certification scheme", "Mobile assessment app"], a: 1, e: "DigComp 3.0 is the first DigComp version with a consolidated Glossary (approximately 120 terms). DigComp 2.2 had no comparable single glossary; definitions were scattered across the document." },
  { i: "d3.22", c: "d3", t: "Dimensions dropped", d: 3, q: "How does DigComp 3.0 treat the 'Dimensions 1–5' architecture used in DigComp 2.1 / 2.2?", o: ["It is preserved unchanged", "It is replaced by a five-component model whose new components include competence statements and learning outcomes", "Only Dimension 4 (KSA examples) is kept", "Dimensions are renumbered 1–8"], a: 1, e: "The 'Dimensions 1–5' label is dropped. DigComp 3.0 lists five framework components: definition, areas, competences, proficiency levels, learning outcomes. The 2.2 'use cases' (Dimension 5) and 'KSA examples' (Dimension 4) are replaced by 362 competence statements + 523 learning outcomes." },
  { i: "d3.23", c: "d3", t: "EPSO transition", d: 2, q: "For the EPSO AD5/2026 competition, which framework version is referenced in the Notice of Competition (EPSO/AD/427/26)?", o: ["DigComp 1.0", "DigComp 2.0", "DigComp 2.2", "DigComp 3.0"], a: 2, e: "EPSO/AD/427/26 explicitly references DigComp 2.2. DigComp 3.0 was published only weeks before the application window opened (5 February – 10 March 2026). Candidates should master 2.2 first; 3.0 is supplementary." },
  { i: "d3.24", c: "d3", t: "Digital Decade target", d: 2, q: "DigComp 3.0 underpins the EU's Digital Decade target — set by Decision (EU) 2022/2481 — of having at least basic digital skills among:", o: ["50% of 16–74 year olds by 2025", "60% of all citizens by 2027", "80% of 16–74 year olds by 2030", "100% of public-sector workers by 2030"], a: 2, e: "The Digital Decade Policy Programme (Decision (EU) 2022/2481) sets the 80% basic-digital-skills target by 2030 for those aged 16–74. DigComp is the conceptual basis of the Digital Skills Indicator used to monitor progress (baseline 56% in 2023)." },
  { i: "d3.25", c: "d3", t: "Council adoption", d: 3, q: "Has DigComp 3.0 been formally adopted by the Council of the European Union as binding law?", o: ["Yes, by a Council Recommendation in 2025", "Yes, by an EU Regulation", "No — it is a JRC science-for-policy reference; the 2018 Council Recommendation on Key Competences provides the legal backdrop", "Yes, by a Council Decision"], a: 2, e: "DigComp has never been formally adopted by Council; the 2018 Council Recommendation on Key Competences for Lifelong Learning provides the legal backdrop without specifying a DigComp version. DigComp 3.0 is an authoritative JRC reference, not binding EU law." },
  { i: "d3.26", c: "d3", t: "Sister frameworks", d: 2, q: "DigComp 3.0 covers citizens. Which related framework targets educators specifically?", o: ["DigCompOrg", "DigCompEdu", "EntreComp", "DigComp at Work"], a: 1, e: "DigCompEdu addresses educators. DigCompOrg targets organisations, EntreComp covers entrepreneurship, and DigComp at Work focuses on workplace skills. None of these sister frameworks has been updated to a 3.0 line at the time of DigComp 3.0's publication." }
];
